export const QUESTION_COLUMN_DROP_ZONE = 'QUESTION_COLUMN_DROP_ZONE';
export const QUESTION_COLUMN = 'QUESTION_COLUMN';

export const QUESTION_ITEM_DROP_ZONE = 'QUESTION_ITEM_DROP_ZONE';
export const QUESTION_ITEM = 'QUESTION_ITEM';

export const QUESTION_DROP_ZONE = 'QUESTION_DROP_ZONE';
export const QUESTION_SECOND_DROP_ZONE = 'QUESTION_SECOND_DROP_ZONE';
export const QUESTION_BLOCK_DROP_ZONE = 'QUESTION_BLOCK_DROP_ZONE';