export const SET_NEW_QUESTIONS_ORDER = 'SET_NEW_QUESTIONS_ORDER';
export const CAN_DRAG = 'CAN_DRAG';
export const SET_NEW_COLUMNS_ORDER = 'SET_NEW_COLUMNS_ORDER';
export const SET_NEW_QUESTIONS = 'SET_NEW_QUESTIONS';